# configuration file for Travis-CI
# https://travis-ci.org

language: java

sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew assemble check jacocoTestReport coveralls

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/