# configuration file for Travis-CI
# https://travis-ci.org

language: java

sudo: false

jdk:
  - oraclejdk8

script:
  - curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - ./gradlew check jacocoTestReport coveralls
  - export CODACY_PROJECT_TOKEN=1714e1023d82400591d2d3c1a6bd94ae
  - codacy-coverage-reporter -l Java -r coverage.xml
